[appendix]
== Git Alternatives


Git is not the only popular DVCS, but it is the most popular. Here is
a quick comparison of the other major DVCSes, from both technical and
cultural viewpoints. 

===== Darcs

Darcs supports the same set of basic operations as Git does, but
differs internally in that it manages a set of patches independently
rather than as a connected directed acyclic graph (DAG). In other
words, darcs allows you to create a set of changes and then push
individual patches from that set without the need to rewrite the
history graph. This internal structure makes branching even cheaper
than with git, one of the most touted benefits of using git. There is
controversy around "cherry-picking" within the world of DVCS, but this
part of darcs makes cherry picking trivial. Darcs is written in
Haskell. Unfortunately, as of this writing, there is no strong
equivalent to GitHub for darcs hosting. The leading candidate
"darcsden.com" has a copyright notice from 2011 and most projects show
activity no later than 2011 as well. Darcs uses the GPL license. 

===== Bazaar (bzr)

Bazaar (which uses the command line command "bzr") is an open source
DVCS that offers the majority of operations that Git offers. Bazaar is
sponsored by Canonical, the company which develops Ubuntu, the most
popular distribution of Linux. Canonical offers a functional hosting
service called Launchpad.net which offers good code management across
teams but does not have near the polish of GitHub. Bazaar uses
sequential commit numbers (1,2,3) rather than git-style SHA hashes
(d670460b4b4a..., 1f7a7a472abf...), which means it is easier to tell
which commit comes before or after another; you are simply comparing
an integer to another integer, but this does add complexity (handled
by the bzr tools generally) to managing these commit numbers when you
start introducing other team member commits. Another technical
difference is that directories are first class objects, meaning bzr
can rename directories and this operation is stored as a rename
operation in the commit log. Compare this to Git which does not store
directories inside commit history and notice how git requires you to
place files like ".gitkeep" in order to maintain empty
directories. Mark Shuttlesworth, the founder of Ubuntu, has written at
length about the benefits of renaming and how bzr wins against other
DVCS, including git. Bzr is written in Python and licensed under the
GPLv2. Bazaar was originally forked from the arch DVCS. 

===== Mercurial (hg)

Mercurial (which uses the command line command "hg") is another DVCS,
offering much of the same functionality as git. Unlike git, Mercurial
is distributed as a single monolithic binary instead of multiple git
commands (over 140 individual commands, depending on which build
version you are using of git). You can tell git came from the Linux
world which favors small chainable commands, but let's not go so far
to say that Mercurial was designed in the basements of Redmond,
WA. Mercurial also uses a DAG to keep change history, like
Git. Mercurial favors immutable histories, meaning there are no tools
to rewrite history like the "git revert" command. Mercurial has the
best code hosting alternative to GitHub in BitBucket.org, a service of
Atlassian. Mercurial is licensed under the GPLv2 and is written in
Python. 

===== Monotone

If a movie studio ever decides to remake "Back to the Future" with the
main character named Git instead of Marty, there will be a scene where
Git sees his hand disappearing in front of his eyes while strumming a
guitar, as Linus Torvalds dances and falls in love with Monotone,
dooming us all to a future world without Git. Fortunately, right as
Linus is about to falls deeply in love with Monotone, she says: "So,
you know, my father Bjarne Stroustrup said..." Looking incredulous,
Linus interrupts her and says: "Wait! You're C\+\+?!?!" And, he rushes
out, leaving Monotone alone on the dance floor, securing our future
with Git and GitHub. Back to reality, Monotone was initially favored
by Linus as the replacement to BitKeeper and CVS within the Linux
kernel community, but Linus could never overcome his revulsion to the
performance of C++, the language in which Monotone was
written. Ideologically, Linus agrees with the ommission of cherry
picking in Monotone, though ironically this is a feature available in
the git of today. Unfortunately, Monotone has lost momentum; for
example, the mailing list for the Monotone Eclipse plugin has seen no
activity since 2008. Monotone is licensed under the GPL. 

===== BitKeeper

BitKeeper was the early inspiration for many of these open source
DVCSes. The maintainers of the Linux kernel used BitKeeper for a short
while, but differences over its closed source licensing inspired Linux
kernel developers to seek out an alternative and resulted in Linus
building his own, now called Git. Unfortunately, for many open source
developers, a closed source system which manages their source code is
a no go, and there are many viable alternatives offering the same
features as BitKeeper, so while BitKeeper continues to have some
traction in the enterprise, there are very few open source projects
using it. 
