[[creating-account]]
== Creating a Github Account

It seems odd to have a whole chapter for this, but I'm assuming that
this will be an 8 page chapter.

=== Selecting a GitHub Plan

Selecting the appropriate Github plan is...

Sidebar: How most organizations signup for Github?

==== Types of Github Plans

Table Figure: Compare the Features of Each Plan

===== Free

It costs nothing to sign-up for a Github account.

===== Personal

Once you start creating private repositories, you'll need a personal plan.

===== Organization

If you need to share private projects with more than X people, you'll
need an organization pan.

==== Choosing the Right Plan

Figure: A Decision Tree for What Plan to Choose

===== Open Source Development

If you are only contributing to open source projects, you can probably
get by with a Free plan.

===== Small Project Development

Small teams of less than 10 people working as individuals are best
served by personal plans.

===== Startups, Small to Medium Businesses

Once a company starts to depend on Github for coding and collaboration
it will make sense to use an Organziation plan.

===== Enterprise-scale Development

If you have hundreds or thousands of developers, you may not want to
use either of these plans.  In these situations, Github offers a
service called Github Enterprise.

=== Setting Up Your Accounts

If you are new to Github, this section has been designed to walk you
through the process of setting up an account.

==== User Accounts versus Organization Accounts

The previous section goes into detail where to start

==== Signing up for your User Account

How to sign up for an individual user account.

==== Setting up an Organization Account

How to sign up for an organizational account.

=== Exploring Account Security

==== Reseting Your Password

Simple screenshot and instructions.

==== SSH vs HTTPS

Which one should you use?
