=== GitHub.com: a town square for the coder community.

There were other Git hosting services before GitHub.com. But, GitHub was the first to build a rabid community
around Git. GitHub.com became the town square where the coding cognoscenti gathered to discuss, where the 
coding enfants played with new ideas that would become the future of our world. GitHub.com has become 
the playground and the guild where ideas flourish and grow like no other online community for software developers.
As such, it is important to give a tour of GitHub.com and learn how to navigate like a member of the inner circle.

=== An overview of GitHub.com

GitHub.com, like most online communities, grows each day, with new sections added to fulfill previously unknown
needs. As a software developer, we assume you already know you way around most of the normal places, so this chapter
serves to illumnate some less well known places on GitHub.com

==== Security

If you have been using GUI clients for GitHub, it is likely that you noticed there were options for downloading via
SSH, but never have used anything beyond HTTPS download. The graphical client, like GitHub for Mac, or GitHub for
Windows use HTTPS as their default because they don't require any configuration on GitHub.com to provide you with
access. This chapter will tell you why this is a bad idea, and why switching to SSH keys is a simple and smart thing to
do.

==== Keyboard Shortcuts

Why do you love your favorite editor the way you do? Whether it be Emacs, Vim, XCode, Android Studio, TextMate or another, 
the main reason you love it is that it saves you time. Smart editors make complicated tasks easier. Each editor has 
its own metaphor, with Android Studio offering to automatically insert import code when a missing package is discovered, 
to the fully immersive experience of Emacs with unlimited customization no matter what language you are editing. 
GitHub.com is a community tool created by coders and it offers the same benefits as your favorite editor by making
its core service (exploring code) faster than alternatives. One such way it does this is by offering keyboard
shortcuts. 

===== Getting started with shortcuts

To lea
