[preface]
== Preface

* Git, What is it?


* Github, What is it?

GitHub 

* Chris' introduction

* Ben's introduction

* Audience for this book

This book should be an interesting source of information for people
who have used Git or GitHub and want to "level-up" their skills
related to these technologies. People without any experience using
GitHub or Git should start with an introductory book on these
technologies. 

Much of the book focuses on the technical capabilities exposed by
GitHub and the powerful GitHub API. Perhaps you feel
constrained by using Git only from within a certain toolset; for
example, if you are an Eclipse developer accidentally using Git to
manage your Android source code and want to unlock Git in other places
in your life as a developer, this book provides a wider vista to learn
about the power of Git and GitHub. If you have fallen into using Git
for your own projects and are now interested in using Git within a
larger community, this book can teach you all about "social coding."
This book provides a stepping stone for software developers who have
used other distributed version control systems and are looking for a
bridge to using their skills with Git and within a web service like
GitHub. Like any seasoned developer, automation of your tools is
important to you, and this book provides recipes for taking mundane
tasks and converting them into automated services, and we show how to
do this using a variety of languages talking to the GitHub API. This
book provides a concise and directed approach to learning about the
various features and tools offered by GitHub. 

And, the bigger opportunity for readers of this book is to find a way
to transform your coding experience using the "GitHub way." GitHub is
phenomenom in the startup world, bootstrapping itself to 1.7M users
before taking any investment, and this success came about in part from
their distinct and vibrant culture. "GitHubbers" eat their own dog
food by using the same tools they offer to their customers. These
tools, like "pull requests" and "issues," stand in stark contrast and
often replace tools other companies rely upon, like email. If you
absorb not only the technical facets of using GitHub but also pay
attention to the cultural and ideological changes offered behind the
tools, you'll very likely see a new way of working in the modern
age. We focus on these "meta" viewpoints as we discuss the tools
themselves to help you see these extra opportunities. 

If you are unfamiliar with the "command line" this book will give you
a firm understanding of how to use it, and we bet you will find great
power there. To make this book accessible to everyone, regardless of
their editor or operating system, many of the programming samples work
within the command line. And, almost every chapter has an associated
repository hosted on GitHub where you can review the code
discussed. Fork away and take these samples into your own projects and
tools!

* Font Conventions

* Github Writing Conventions

* Downloading Code Examples

* Using Code Examples

* Safari Books Online

* How to Contact Us

* Acknowledgements


=== Conventions Used in This Book

The following typographical conventions are used in this book:

_Italic_:: Indicates new terms, URLs, email addresses, filenames, and file extensions.

+Constant width+:: Used for program listings, as well as within paragraphs to refer to program elements such as variable or function names, databases, data types, environment variables, statements, and keywords.

**`Constant width bold`**:: Shows commands or other text that should be typed literally by the user.

_++Constant width italic++_:: Shows text that should be replaced with user-supplied values or by values determined by context.


[TIP]
====
This icon signifies a tip, suggestion, or general note.
====

[WARNING]
====
This icon indicates a warning or caution.
====

=== Using Code Examples
++++
<remark>PROD: Please reach out to author to find out if they will be uploading code examples to oreilly.com or their own site (e.g., GitHub). If there is no code download, delete this whole section. If there is, when you email digidist with the link, let them know what you filled in for title_title (should be as close to book title as possible, i.e., learning_python_2e). This info will determine where digidist loads the files.</remark>
++++

Supplemental material (code examples, exercises, etc.) is available for download at link:$$https://github.com/oreillymedia/title_title$$[].

This book is here to help you get your job done. In general, if example code is offered with this book, you may use it in your programs and documentation. You do not need to contact us for permission unless you’re reproducing a significant portion of the code. For example, writing a program that uses several chunks of code from this book does not require permission. Selling or distributing a CD-ROM of examples from O’Reilly books does require permission. Answering a question by citing this book and quoting example code does not require permission. Incorporating a significant amount of example code from this book into your product’s documentation does require permission.

We appreciate, but do not require, attribution. An attribution usually includes the title, author, publisher, and ISBN. For example: “_Book Title_ by Some Author (O’Reilly). Copyright 2012 Some Copyright Holder, 978-0-596-xxxx-x.”

If you feel your use of code examples falls outside fair use or the permission given above, feel free to contact us at pass:[<email>permissions@oreilly.com</email>].

=== Safari® Books Online

[role = "safarienabled"]
[NOTE]
====
pass:[<ulink role="orm:hideurl:ital" url="http://my.safaribooksonline.com/?portal=oreilly">Safari Books Online</ulink>] is an on-demand digital library that delivers expert pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/content">content</ulink>] in both book and video form from the world&#8217;s leading authors in technology and business.
====

Technology professionals, software developers, web designers, and business and creative professionals use Safari Books Online as their primary resource for research, problem solving, learning, and certification training.

Safari Books Online offers a range of pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/subscriptions">product mixes</ulink>] and pricing programs for pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/organizations-teams">organizations</ulink>], pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/government">government agencies</ulink>], and pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/individuals">individuals</ulink>]. Subscribers have access to thousands of books, training videos, and prepublication manuscripts in one fully searchable database from publishers like O’Reilly Media, Prentice Hall Professional, Addison-Wesley Professional, Microsoft Press, Sams, Que, Peachpit Press, Focal Press, Cisco Press, John Wiley & Sons, Syngress, Morgan Kaufmann, IBM Redbooks, Packt, Adobe Press, FT Press, Apress, Manning, New Riders, McGraw-Hill, Jones & Bartlett, Course Technology, and dozens pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/publishers">more</ulink>]. For more information about Safari Books Online, please visit us pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/">online</ulink>].

=== How to Contact Us

Please address comments and questions concerning this book to the publisher:

++++
<simplelist>
<member>O’Reilly Media, Inc.</member>
<member>1005 Gravenstein Highway North</member>
<member>Sebastopol, CA 95472</member>
<member>800-998-9938 (in the United States or Canada)</member>
<member>707-829-0515 (international or local)</member>
<member>707-829-0104 (fax)</member>
</simplelist>
++++

We have a web page for this book, where we list errata, examples, and any additional information. You can access this page at link:$$http://www.oreilly.com/catalog/<catalog page>$$[].

++++
<remark>Don't forget to update the link above.</remark>
++++

To comment or ask technical questions about this book, send email to pass:[<email>bookquestions@oreilly.com</email>].

For more information about our books, courses, conferences, and news, see our website at link:$$http://www.oreilly.com$$[].

Find us on Facebook: link:$$http://facebook.com/oreilly$$[]

Follow us on Twitter: link:$$http://twitter.com/oreillymedia$$[]

Watch us on YouTube: link:$$http://www.youtube.com/oreillymedia$$[]

=== Acknowledgments

[[preface]]
Preface

* Git, What is it?

* Github, What is it?

* Font Conventions

* Github Writing Conventions

* Downloading Code Examples

* Using Code Examples

* Safari Books Online

* How to Contact Us

* Acknowledgements
