[[preface]]
== Preface

GitHub 

* Chris' introduction

* Ben's introduction

* Audience for this book

=== Introduction

In Oxford, England, The Eagle and Child simmered with creativity in
the 1930s as JRR Tolkien and CS Lewis philosophized and created their
fantasy worlds. Heian court life in 11th century Kyoto, Japan cradled
Murasaki Shibu and produced The Tale of Genji, Japan's greatest novel.
In the 7th century during the Umayyad Caliphate of modern day
Damascus, Syria, glittering Arabic palaces provided fertile ground for
the creation of a new form of poetry, the ghazal ("love poems") the
influence of which still courses through modern Arabic poetry. 

Each era of major creative innovation has been backdropped by a unique
and plumb space where collaboration and creativity flourished. Today,
the collaborative space where some of the world's greatest artists
(artists who also happen to be software developers) have gathered is a
virtual town square, a site called GitHub. 

=== Who You Are

This book should be an interesting source of information for people
who have used Git or GitHub and want to "level-up" their skills
related to these technologies. People without any experience using
GitHub or Git should start with an introductory book on these
technologies. 

You should have a good familiarity with at least one imperative modern
programming language. You don't need to be an expert programmer to
read this book, but having some programming experience and familiarity
with at least one language is essential. 

=== What You Will Learn

Much of the book focuses on the technical capabilities exposed by
GitHub and the powerful GitHub API. Perhaps you feel constrained by
using Git only from within a certain toolset; for example, if you are
an Eclipse developer accidentally using Git to manage your Android
source code and want to unlock Git in other places in your life as a
developer, this book provides a wider vista to learn about the power
of Git and GitHub. If you have fallen into using Git for your own
projects and are now interested in using Git within a larger
community, this book can teach you all about "social coding." This
book provides a stepping stone for software developers who have used
other distributed version control systems and are looking for a bridge
to using their skills with Git and within a web service like GitHub.  

Like any seasoned developer, automation of your tools is important to
you, and this book provides examples of mundane tasks that we then
convert them into automated tools, and we show how to do this using a
variety of languages talking to the GitHub API.  

If you are unfamiliar with the "command line" this book will give you
a firm understanding of how to use it, and we bet you will find great
power there. To make this book accessible to everyone, regardless of
their editor or operating system, many of the programming samples work
within the command line.  

If you absorb not only the technical facets of using GitHub but also
pay attention to the cultural and ideological changes offered behind
the tools, you'll very likely see a new way of working in the modern
age. We focus on these "meta" viewpoints as we discuss the tools
themselves to help you see these extra opportunities. 

Almost every chapter has an associated repository hosted on GitHub
where you can review the code discussed. Fork away and take these
samples into your own projects and tools! 

Finally, we help you write testable API backed code. You will find
ways to embrace the "wabi sabi" of your code: nothing lasts, nothing
is finished and nothing is perfect, especially when using APIs. APIs
will change, APIs must change and your code must adapt quickly to this
reality. Though many developers pretend otherwise, memory is
unrealiable, and your code must be zen: you should be able to come
back to a piece of code a thousand years later and know whether it
works or not without remembering details the implementation. The only way
to have this surety is to write tests that prove success or
failure. Traditionally writing tests is challenging, and especially
when you are testing something backed by an API.  To help you get past
this roadblock, whenever possible, this book shows you how to write
code which is testable and interacts with the GitHub API. 

=== Who This Book is Not For

If you are looking for a discussion of the GitHub API that focuses on
a single language, you will be disappointed to find that we look at
the API through many different languages. We do this to describe the
API from not only the way the GitHub team designed it to work, but the
aspirational way that client library authors made it work within
diverse programming languages and communities. We think there is a lot
to learn from this approach, but if you are interested in only a
specific language and how it works with the GitHub API, this is not
the book for you. 


===== Test Driven



* Font Conventions

* Github Writing Conventions

* Downloading Code Examples

* Using Code Examples

* Safari Books Online

* How to Contact Us

* Acknowledgements

== Preface

=== Conventions Used in This Book

The following typographical conventions are used in this book:

_Italic_:: Indicates new terms, URLs, email addresses, filenames, and file extensions.

+Constant width+:: Used for program listings, as well as within paragraphs to refer to program elements such as variable or function names, databases, data types, environment variables, statements, and keywords.

**`Constant width bold`**:: Shows commands or other text that should be typed literally by the user.

_++Constant width italic++_:: Shows text that should be replaced with user-supplied values or by values determined by context.


[TIP]
====
This icon signifies a tip, suggestion, or general note.
====

[WARNING]
====
This icon indicates a warning or caution.
====

=== Using Code Examples
++++
<remark>PROD: Please reach out to author to find out if they will be uploading code examples to oreilly.com or their own site (e.g., GitHub). If there is no code download, delete this whole section. If there is, when you email digidist with the link, let them know what you filled in for title_title (should be as close to book title as possible, i.e., learning_python_2e). This info will determine where digidist loads the files.</remark>
++++

Supplemental material (code examples, exercises, etc.) is available for download at link:$$https://github.com/oreillymedia/title_title$$[].

This book is here to help you get your job done. In general, if example code is offered with this book, you may use it in your programs and documentation. You do not need to contact us for permission unless you’re reproducing a significant portion of the code. For example, writing a program that uses several chunks of code from this book does not require permission. Selling or distributing a CD-ROM of examples from O’Reilly books does require permission. Answering a question by citing this book and quoting example code does not require permission. Incorporating a significant amount of example code from this book into your product’s documentation does require permission.

We appreciate, but do not require, attribution. An attribution usually includes the title, author, publisher, and ISBN. For example: “_Book Title_ by Some Author (O’Reilly). Copyright 2012 Some Copyright Holder, 978-0-596-xxxx-x.”

If you feel your use of code examples falls outside fair use or the permission given above, feel free to contact us at pass:[<email>permissions@oreilly.com</email>].

=== Safari® Books Online

[role = "safarienabled"]
[NOTE]
====
pass:[<ulink role="orm:hideurl:ital" url="http://my.safaribooksonline.com/?portal=oreilly">Safari Books Online</ulink>] is an on-demand digital library that delivers expert pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/content">content</ulink>] in both book and video form from the world&#8217;s leading authors in technology and business.
====

Technology professionals, software developers, web designers, and business and creative professionals use Safari Books Online as their primary resource for research, problem solving, learning, and certification training.

Safari Books Online offers a range of pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/subscriptions">product mixes</ulink>] and pricing programs for pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/organizations-teams">organizations</ulink>], pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/government">government agencies</ulink>], and pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/individuals">individuals</ulink>]. Subscribers have access to thousands of books, training videos, and prepublication manuscripts in one fully searchable database from publishers like O’Reilly Media, Prentice Hall Professional, Addison-Wesley Professional, Microsoft Press, Sams, Que, Peachpit Press, Focal Press, Cisco Press, John Wiley & Sons, Syngress, Morgan Kaufmann, IBM Redbooks, Packt, Adobe Press, FT Press, Apress, Manning, New Riders, McGraw-Hill, Jones & Bartlett, Course Technology, and dozens pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/publishers">more</ulink>]. For more information about Safari Books Online, please visit us pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/">online</ulink>].

=== How to Contact Us

Please address comments and questions concerning this book to the publisher:

++++
<simplelist>
<member>O’Reilly Media, Inc.</member>
<member>1005 Gravenstein Highway North</member>
<member>Sebastopol, CA 95472</member>
<member>800-998-9938 (in the United States or Canada)</member>
<member>707-829-0515 (international or local)</member>
<member>707-829-0104 (fax)</member>
</simplelist>
++++

We have a web page for this book, where we list errata, examples, and any additional information. You can access this page at link:$$http://www.oreilly.com/catalog/<catalog page>$$[].

++++
<remark>Don't forget to update the link above.</remark>
++++

To comment or ask technical questions about this book, send email to pass:[<email>bookquestions@oreilly.com</email>].

For more information about our books, courses, conferences, and news, see our website at link:$$http://www.oreilly.com$$[].

Find us on Facebook: link:$$http://facebook.com/oreilly$$[]

Follow us on Twitter: link:$$http://twitter.com/oreillymedia$$[]

Watch us on YouTube: link:$$http://www.youtube.com/oreillymedia$$[]

=== Acknowledgments

[[preface]]
Preface

* Git, What is it?

* Github, What is it?

* Font Conventions

* Github Writing Conventions

* Downloading Code Examples

* Using Code Examples

* Safari Books Online

* How to Contact Us

* Acknowledgements
